const TOP_LEVEL_DOMAIN = "https://hubmetalsandtrading.com/";
const PRODUCT_PAGE_ID = 2;
const PRODUCTS = [
	{
		product: "aluminum-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [
			{ type: "1100 Aluminum", content: "" },
			{ type: "2024 Aluminum", content: "" },
			{ type: "7050 Aluminum", content: "" },
			{ type: "2011 Aluminum", content: "" },
			{ type: "2014 Aluminum", content: "" },
			{ type: "2124 Aluminum", content: "" },
			{ type: "2219 Aluminum", content: "" },
			{ type: "3003 Aluminum", content: "" },
			{ type: "6013 Aluminum", content: "" },
			{ type: "6061 Aluminum", content: "" },
			{ type: "6063 Aluminum", content: "" },
			{ type: "6262 Aluminum", content: "" },
			{ type: "7050 Aluminum", content: "" },
			{ type: "7075 Aluminum", content: "" },
			{ type: "7475 Aluminum", content: "" },
			{ type: "cast plate", content: "" },
		],
	},
	{
		product: "alloy-steel",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [
			{ type: "4130 Steel", content: "" },
			{ type: "4140 Steel", content: "" },
			{ type: "4330 Steel", content: "" },
			{ type: "4340 Steel", content: "" },
			{ type: "6150 Steel", content: "" },
			{ type: "8740 Steel", content: "" },
			{ type: "9310 Steel", content: "" },
			{ type: "52100 Steel", content: "" },
		],
	},
	{
		product: "stainless-steel",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [
			{ type: "301 Stainless Steel", content: "" },
			{ type: "302 Stainless Steel", content: "" },
			{ type: "303 Stainless Steel", content: "" },
			{ type: "304 Stainless Steel", content: "" },
			{ type: "310 Stainless Steel", content: "" },
			{ type: "316 Stainless Steel", content: "" },
			{ type: "321 Stainless Steel", content: "" },
			{ type: "347 Stainless Steel", content: "" },
			{ type: "410 Stainless Steel", content: "" },
			{ type: "416 Stainless Steel", content: "" },
			{ type: "418 Stainless Steel", content: "" },
			{ type: "440C Stainless Steel", content: "" },
			{ type: "PH Stainless Steel", content: "" },
		],
	},
	{
		product: "titanium-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "brass-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "bronze-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "copper-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "carbon-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "magnesium-alloy",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
	{
		product: "tungsten",
		shapes: [
			{ type: "bar", content: "" },
			{ type: "sheet", content: "" },
			{ type: "plate", content: "" },
			{ type: "tubing", content: "" },
			{ type: "pipe", content: "" },
			{ type: "forging", content: "" },
		],
		types: [],
	},
];

module.exports = {
	TOP_LEVEL_DOMAIN,
	PRODUCTS,
};
